"""Add monthly_budget_from_net to Users table

Revision ID: 30b68c301740
Revises: 4f44bac98060
Create Date: 2020-05-21 19:48:18.434802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b68c301740'
down_revision = '4f44bac98060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_budget_from_net', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_budget_from_net')
    # ### end Alembic commands ###
