"""Update foreign key in Transactions table

Revision ID: 39c5b09c883a
Revises: d54338d338cb
Create Date: 2020-05-06 12:39:42.089801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c5b09c883a'
down_revision = 'd54338d338cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category_id', sa.String(length=50), nullable=True))
    op.drop_constraint('transactions_category_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_category_fkey', 'transactions', 'categories', ['category'], ['name'])
    op.drop_column('transactions', 'category_id')
    # ### end Alembic commands ###
