"""Add currency field to transaction

Revision ID: 4f44bac98060
Revises: 35a3b60fa3aa
Create Date: 2020-05-12 17:05:29.075933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f44bac98060"
down_revision = "35a3b60fa3aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("currency", sa.String(length=3), nullable=True)
    )
    op.execute("UPDATE transactions SET currency = 'CAD'")
    op.alter_column("transactions", "currency", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "currency")
    # ### end Alembic commands ###
