"""Add Categories table

Revision ID: 5cd0307daf9a
Revises: 7f43e93ec1f9
Create Date: 2020-05-06 12:33:59.487847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd0307daf9a'
down_revision = '7f43e93ec1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('transactions', sa.Column('category', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'transactions', 'categories', ['category'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category')
    op.drop_table('categories')
    # ### end Alembic commands ###
