"""Add indexing to User username

Revision ID: 644ed7fcad19
Revises: 
Create Date: 2019-07-14 21:43:30.113735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644ed7fcad19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
