"""add monthly budget to User

Revision ID: 7bef7921341b
Revises: 25419a0ccafe
Create Date: 2019-09-24 17:06:59.127761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bef7921341b'
down_revision = '25419a0ccafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_budget', sa.Numeric(scale=2, decimal_return_scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_budget')
    # ### end Alembic commands ###
