"""Update default currency to string

Revision ID: 7f43e93ec1f9
Revises: 508b316d467e
Create Date: 2019-12-30 19:21:38.023217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f43e93ec1f9'
down_revision = '508b316d467e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_currency')
    # ### end Alembic commands ###
