"""Make Transaction amount and source non-nullable

Revision ID: 947744eafb69
Revises: b77731b8f8cd
Create Date: 2019-10-25 15:31:29.304509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947744eafb69'
down_revision = 'b77731b8f8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'source',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'source',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
