"""Fix foreign key constraints again

Revision ID: a3e235d7d768
Revises: cd19c43854a6
Create Date: 2020-05-06 13:06:40.903000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e235d7d768'
down_revision = 'cd19c43854a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_category_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_category_fkey', 'transactions', 'categories', ['category'], ['name'])
    op.drop_column('transactions', 'category_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    op.drop_column('categories', 'id')
    # ### end Alembic commands ###
