"""Update primary key in Categories table

Revision ID: d54338d338cb
Revises: 5cd0307daf9a
Create Date: 2020-05-06 12:38:44.179070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54338d338cb'
down_revision = '5cd0307daf9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'id')
    # ### end Alembic commands ###
