"""Remove Categories table

Revision ID: ea74e4b8eba6
Revises: a3e235d7d768
Create Date: 2020-05-06 13:19:35.822829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea74e4b8eba6'
down_revision = 'a3e235d7d768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_category_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_category_fkey', 'transactions', 'categories', ['category'], ['name'])
    op.create_table('categories',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='categories_pkey')
    )
    # ### end Alembic commands ###
